version: '3.8'

services:
  securevault-app:
    build: .
    container_name: securevault-app
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - PORT=5005
      - DB_TYPE=mysql
      - DB_HOST=securevault-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=securevault_db
      - SECRET_KEY=prod_securevault_zero_trust_key_2026_!
      - MASTER_ENCRYPTION_KEY=z7kM1xW4qP9_vR8tL2bY5eN0sH3uA6cI9gJ1fD4oX7k=
    depends_on:
      - securevault-db
    networks:
      - securevault-network

  securevault-db:
    image: mysql:8.0
    container_name: securevault-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=securevault_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - securevault-network

networks:
  securevault-network:
    driver: bridge

volumes:
  mysql-data:
