"""
SecureVault APT Threat Actor Profiles Catalog
Comprehensive database of Advanced Persistent Threat (APT) groups, nation-state actors, TTPs, and targeted industries.
"""

APT_ACTOR_PROFILES_CATALOG = [
    {
        'actor_id': 'ACT-001',
        'actor_code': 'APT28',
        'known_aliases': 'Fancy Bear / Strontium / Forest Blizzard',
        'attributed_origin': 'Russia (GRU)',
        'targeted_sectors': ['Government', 'Defense', 'Energy', 'Media'],
        'associated_mitre_ttps': ['T1566.001', 'T1059.001', 'T1003', 'T1071'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """High-profile cyber espionage operations targeting international defense entities and election infrastructure.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-002',
        'actor_code': 'APT29',
        'known_aliases': 'Cozy Bear / Nobelium / Midnight Blizzard',
        'attributed_origin': 'Russia (SVR)',
        'targeted_sectors': ['Government', 'Think Tanks', 'IT Providers', 'Cloud'],
        'associated_mitre_ttps': ['T1195.002', 'T1078', 'T1098', 'T1556'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Stealthy supply chain and cloud identity compromises targeting diplomatic and foreign policy institutions.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-003',
        'actor_code': 'Lazarus Group',
        'known_aliases': 'HIDDEN COBRA / Zinc',
        'attributed_origin': 'North Korea (RGB)',
        'targeted_sectors': ['Financial', 'Cryptocurrency', 'Defense', 'Aerospace'],
        'associated_mitre_ttps': ['T1566.002', 'T1486', 'T1055', 'T1048'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Financially motivated cryptocurrency thefts, SWIFT network attacks, and destructive ransomware campaigns.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-004',
        'actor_code': 'APT41',
        'known_aliases': 'Double Dragon / Wicked Panda',
        'attributed_origin': 'China (MSS)',
        'targeted_sectors': ['Healthcare', 'Telecom', 'Gaming', 'Technology'],
        'associated_mitre_ttps': ['T1190', 'T1059.003', 'T1036', 'T1567'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Dual espionage and cybercrime operations leveraging zero-day web application vulnerabilities.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-005',
        'actor_code': 'Volt Typhoon',
        'known_aliases': 'Vanguard Panda / Bronze Silhouette',
        'attributed_origin': 'China (State-Sponsored)',
        'targeted_sectors': ['Critical Infrastructure', 'Communications', 'Energy', 'Transportation'],
        'associated_mitre_ttps': ['T1078', 'T1218', 'T1021.002', 'T1046'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Living-off-the-land stealth pre-positioning within western critical infrastructure networks.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-006',
        'actor_code': 'Sandworm Team',
        'known_aliases': 'Voodoo Bear / Seashell Blizzard',
        'attributed_origin': 'Russia (GRU 74455)',
        'targeted_sectors': ['Energy Grid', 'Government', 'Logistics', 'Utilities'],
        'associated_mitre_ttps': ['T1485', 'T1486', 'T1053', 'T1087'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Destructive malware deployments targeting electrical grids, satellite terminals, and critical operational technology.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-007',
        'actor_code': 'FIN7',
        'known_aliases': 'Carbanak Group',
        'attributed_origin': 'Eastern Europe (Cybercrime)',
        'targeted_sectors': ['Retail', 'Hospitality', 'Restaurant Chains', 'Banking'],
        'associated_mitre_ttps': ['T1566.001', 'T1059.005', 'T1027', 'T1041'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Point-of-Sale (POS) malware campaigns and financial extortion operations stealing payment card data.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-008',
        'actor_code': 'LockBit Supporter',
        'known_aliases': 'LockBit 3.0 Ransomware Gang',
        'attributed_origin': 'Transnational (Cybercrime)',
        'targeted_sectors': ['Healthcare', 'Manufacturing', 'Finance', 'Education'],
        'associated_mitre_ttps': ['T1486', 'T1562.001', 'T1070', 'T1567'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Ransomware-as-a-Service (RaaS) triple extortion syndicate operating automated affiliate data leak sites.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-009',
        'actor_code': 'BlackCat / ALPHV',
        'known_aliases': 'ALPHV Ransomware Syndicate',
        'attributed_origin': 'Transnational (Cybercrime)',
        'targeted_sectors': ['Critical Infrastructure', 'Healthcare', 'Legal', 'Defense'],
        'associated_mitre_ttps': ['T1486', 'T1059.001', 'T1003', 'T1048'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Rust-based high-speed multi-threaded ransomware deployed against large enterprise hybrid environments.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-010',
        'actor_code': 'Scattered Spider',
        'known_aliases': 'Octo Tempest / UNC3944',
        'attributed_origin': 'Western Cybercrime Syndicate',
        'targeted_sectors': ['Telecom', 'Gaming', 'BPO', 'Financial'],
        'associated_mitre_ttps': ['T1566.003', 'T1556', 'T1078', 'T1098'],
        'threat_rating': 'CRITICAL',
        'operational_summary': """Social engineering, SIM swapping, and identity provider credential harvesting targeting enterprise helpdesks.""",
        'active_status': True
    },
    {
        'actor_id': 'ACT-011',
        'actor_code': 'APT-EXT-011',
        'known_aliases': 'Advanced Threat Cluster #011',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-012',
        'actor_code': 'APT-EXT-012',
        'known_aliases': 'Advanced Threat Cluster #012',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-013',
        'actor_code': 'APT-EXT-013',
        'known_aliases': 'Advanced Threat Cluster #013',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-014',
        'actor_code': 'APT-EXT-014',
        'known_aliases': 'Advanced Threat Cluster #014',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-015',
        'actor_code': 'APT-EXT-015',
        'known_aliases': 'Advanced Threat Cluster #015',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-016',
        'actor_code': 'APT-EXT-016',
        'known_aliases': 'Advanced Threat Cluster #016',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-017',
        'actor_code': 'APT-EXT-017',
        'known_aliases': 'Advanced Threat Cluster #017',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-018',
        'actor_code': 'APT-EXT-018',
        'known_aliases': 'Advanced Threat Cluster #018',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-019',
        'actor_code': 'APT-EXT-019',
        'known_aliases': 'Advanced Threat Cluster #019',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-020',
        'actor_code': 'APT-EXT-020',
        'known_aliases': 'Advanced Threat Cluster #020',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-021',
        'actor_code': 'APT-EXT-021',
        'known_aliases': 'Advanced Threat Cluster #021',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-022',
        'actor_code': 'APT-EXT-022',
        'known_aliases': 'Advanced Threat Cluster #022',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-023',
        'actor_code': 'APT-EXT-023',
        'known_aliases': 'Advanced Threat Cluster #023',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-024',
        'actor_code': 'APT-EXT-024',
        'known_aliases': 'Advanced Threat Cluster #024',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-025',
        'actor_code': 'APT-EXT-025',
        'known_aliases': 'Advanced Threat Cluster #025',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-026',
        'actor_code': 'APT-EXT-026',
        'known_aliases': 'Advanced Threat Cluster #026',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-027',
        'actor_code': 'APT-EXT-027',
        'known_aliases': 'Advanced Threat Cluster #027',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-028',
        'actor_code': 'APT-EXT-028',
        'known_aliases': 'Advanced Threat Cluster #028',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-029',
        'actor_code': 'APT-EXT-029',
        'known_aliases': 'Advanced Threat Cluster #029',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-030',
        'actor_code': 'APT-EXT-030',
        'known_aliases': 'Advanced Threat Cluster #030',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-031',
        'actor_code': 'APT-EXT-031',
        'known_aliases': 'Advanced Threat Cluster #031',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-032',
        'actor_code': 'APT-EXT-032',
        'known_aliases': 'Advanced Threat Cluster #032',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-033',
        'actor_code': 'APT-EXT-033',
        'known_aliases': 'Advanced Threat Cluster #033',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-034',
        'actor_code': 'APT-EXT-034',
        'known_aliases': 'Advanced Threat Cluster #034',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-035',
        'actor_code': 'APT-EXT-035',
        'known_aliases': 'Advanced Threat Cluster #035',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-036',
        'actor_code': 'APT-EXT-036',
        'known_aliases': 'Advanced Threat Cluster #036',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-037',
        'actor_code': 'APT-EXT-037',
        'known_aliases': 'Advanced Threat Cluster #037',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-038',
        'actor_code': 'APT-EXT-038',
        'known_aliases': 'Advanced Threat Cluster #038',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-039',
        'actor_code': 'APT-EXT-039',
        'known_aliases': 'Advanced Threat Cluster #039',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-040',
        'actor_code': 'APT-EXT-040',
        'known_aliases': 'Advanced Threat Cluster #040',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-041',
        'actor_code': 'APT-EXT-041',
        'known_aliases': 'Advanced Threat Cluster #041',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-042',
        'actor_code': 'APT-EXT-042',
        'known_aliases': 'Advanced Threat Cluster #042',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-043',
        'actor_code': 'APT-EXT-043',
        'known_aliases': 'Advanced Threat Cluster #043',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-044',
        'actor_code': 'APT-EXT-044',
        'known_aliases': 'Advanced Threat Cluster #044',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-045',
        'actor_code': 'APT-EXT-045',
        'known_aliases': 'Advanced Threat Cluster #045',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-046',
        'actor_code': 'APT-EXT-046',
        'known_aliases': 'Advanced Threat Cluster #046',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-047',
        'actor_code': 'APT-EXT-047',
        'known_aliases': 'Advanced Threat Cluster #047',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-048',
        'actor_code': 'APT-EXT-048',
        'known_aliases': 'Advanced Threat Cluster #048',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-049',
        'actor_code': 'APT-EXT-049',
        'known_aliases': 'Advanced Threat Cluster #049',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-050',
        'actor_code': 'APT-EXT-050',
        'known_aliases': 'Advanced Threat Cluster #050',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-051',
        'actor_code': 'APT-EXT-051',
        'known_aliases': 'Advanced Threat Cluster #051',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-052',
        'actor_code': 'APT-EXT-052',
        'known_aliases': 'Advanced Threat Cluster #052',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-053',
        'actor_code': 'APT-EXT-053',
        'known_aliases': 'Advanced Threat Cluster #053',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-054',
        'actor_code': 'APT-EXT-054',
        'known_aliases': 'Advanced Threat Cluster #054',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-055',
        'actor_code': 'APT-EXT-055',
        'known_aliases': 'Advanced Threat Cluster #055',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-056',
        'actor_code': 'APT-EXT-056',
        'known_aliases': 'Advanced Threat Cluster #056',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-057',
        'actor_code': 'APT-EXT-057',
        'known_aliases': 'Advanced Threat Cluster #057',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-058',
        'actor_code': 'APT-EXT-058',
        'known_aliases': 'Advanced Threat Cluster #058',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-059',
        'actor_code': 'APT-EXT-059',
        'known_aliases': 'Advanced Threat Cluster #059',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-060',
        'actor_code': 'APT-EXT-060',
        'known_aliases': 'Advanced Threat Cluster #060',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-061',
        'actor_code': 'APT-EXT-061',
        'known_aliases': 'Advanced Threat Cluster #061',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-062',
        'actor_code': 'APT-EXT-062',
        'known_aliases': 'Advanced Threat Cluster #062',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-063',
        'actor_code': 'APT-EXT-063',
        'known_aliases': 'Advanced Threat Cluster #063',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-064',
        'actor_code': 'APT-EXT-064',
        'known_aliases': 'Advanced Threat Cluster #064',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-065',
        'actor_code': 'APT-EXT-065',
        'known_aliases': 'Advanced Threat Cluster #065',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-066',
        'actor_code': 'APT-EXT-066',
        'known_aliases': 'Advanced Threat Cluster #066',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-067',
        'actor_code': 'APT-EXT-067',
        'known_aliases': 'Advanced Threat Cluster #067',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-068',
        'actor_code': 'APT-EXT-068',
        'known_aliases': 'Advanced Threat Cluster #068',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-069',
        'actor_code': 'APT-EXT-069',
        'known_aliases': 'Advanced Threat Cluster #069',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-070',
        'actor_code': 'APT-EXT-070',
        'known_aliases': 'Advanced Threat Cluster #070',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-071',
        'actor_code': 'APT-EXT-071',
        'known_aliases': 'Advanced Threat Cluster #071',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-072',
        'actor_code': 'APT-EXT-072',
        'known_aliases': 'Advanced Threat Cluster #072',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-073',
        'actor_code': 'APT-EXT-073',
        'known_aliases': 'Advanced Threat Cluster #073',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-074',
        'actor_code': 'APT-EXT-074',
        'known_aliases': 'Advanced Threat Cluster #074',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-075',
        'actor_code': 'APT-EXT-075',
        'known_aliases': 'Advanced Threat Cluster #075',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-076',
        'actor_code': 'APT-EXT-076',
        'known_aliases': 'Advanced Threat Cluster #076',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-077',
        'actor_code': 'APT-EXT-077',
        'known_aliases': 'Advanced Threat Cluster #077',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-078',
        'actor_code': 'APT-EXT-078',
        'known_aliases': 'Advanced Threat Cluster #078',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-079',
        'actor_code': 'APT-EXT-079',
        'known_aliases': 'Advanced Threat Cluster #079',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-080',
        'actor_code': 'APT-EXT-080',
        'known_aliases': 'Advanced Threat Cluster #080',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-081',
        'actor_code': 'APT-EXT-081',
        'known_aliases': 'Advanced Threat Cluster #081',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-082',
        'actor_code': 'APT-EXT-082',
        'known_aliases': 'Advanced Threat Cluster #082',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-083',
        'actor_code': 'APT-EXT-083',
        'known_aliases': 'Advanced Threat Cluster #083',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
    {
        'actor_id': 'ACT-084',
        'actor_code': 'APT-EXT-084',
        'known_aliases': 'Advanced Threat Cluster #084',
        'attributed_origin': 'Classified Threat Origin',
        'targeted_sectors': ['Financial Services', 'Defense Industrial Base', 'Cloud Telemetry'],
        'associated_mitre_ttps': ['T1190', 'T1059', 'T1078', 'T1486', 'T1566'],
        'threat_rating': 'HIGH',
        'operational_summary': 'Persistent threat actor conducting stealth reconnaissance and credential exfiltration campaigns across enterprise clouds.',
        'active_status': True
    },
]

def get_all_apt_profiles():
    return APT_ACTOR_PROFILES_CATALOG

def get_apt_by_code(code: str):
    clean = code.strip().upper()
    for a in APT_ACTOR_PROFILES_CATALOG:
        if a['actor_code'].upper() == clean:
            return a
    return None
