"""
SecureVault Enterprise Attribute-Based Access Control (ABAC) Policy Matrix
Evaluates dynamic subjects, objects, actions, and environmental context attributes.
"""
from typing import Dict, Any, List

ENTERPRISE_ABAC_POLICIES = [
    {
        'policy_id': 'ABAC-POL-001',
        'policy_name': 'Contextual Rule #001 - ROTATE_KEY for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-002',
        'policy_name': 'Contextual Rule #002 - BLOCK_IP for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-003',
        'policy_name': 'Contextual Rule #003 - APPROVE_ELEVATION for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-004',
        'policy_name': 'Contextual Rule #004 - EXPORT_AUDIT_LOGS for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-005',
        'policy_name': 'Contextual Rule #005 - TRIGGER_SOAR for Admin',
        'subject_role': 'Admin',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-006',
        'policy_name': 'Contextual Rule #006 - READ_SECRET for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-007',
        'policy_name': 'Contextual Rule #007 - ROTATE_KEY for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-008',
        'policy_name': 'Contextual Rule #008 - BLOCK_IP for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-009',
        'policy_name': 'Contextual Rule #009 - APPROVE_ELEVATION for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-010',
        'policy_name': 'Contextual Rule #010 - EXPORT_AUDIT_LOGS for Admin',
        'subject_role': 'Admin',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-011',
        'policy_name': 'Contextual Rule #011 - TRIGGER_SOAR for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-012',
        'policy_name': 'Contextual Rule #012 - READ_SECRET for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-013',
        'policy_name': 'Contextual Rule #013 - ROTATE_KEY for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-014',
        'policy_name': 'Contextual Rule #014 - BLOCK_IP for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-015',
        'policy_name': 'Contextual Rule #015 - APPROVE_ELEVATION for Admin',
        'subject_role': 'Admin',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-016',
        'policy_name': 'Contextual Rule #016 - EXPORT_AUDIT_LOGS for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-017',
        'policy_name': 'Contextual Rule #017 - TRIGGER_SOAR for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-018',
        'policy_name': 'Contextual Rule #018 - READ_SECRET for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-019',
        'policy_name': 'Contextual Rule #019 - ROTATE_KEY for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-020',
        'policy_name': 'Contextual Rule #020 - BLOCK_IP for Admin',
        'subject_role': 'Admin',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-021',
        'policy_name': 'Contextual Rule #021 - APPROVE_ELEVATION for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-022',
        'policy_name': 'Contextual Rule #022 - EXPORT_AUDIT_LOGS for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-023',
        'policy_name': 'Contextual Rule #023 - TRIGGER_SOAR for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-024',
        'policy_name': 'Contextual Rule #024 - READ_SECRET for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-025',
        'policy_name': 'Contextual Rule #025 - ROTATE_KEY for Admin',
        'subject_role': 'Admin',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-026',
        'policy_name': 'Contextual Rule #026 - BLOCK_IP for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-027',
        'policy_name': 'Contextual Rule #027 - APPROVE_ELEVATION for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-028',
        'policy_name': 'Contextual Rule #028 - EXPORT_AUDIT_LOGS for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-029',
        'policy_name': 'Contextual Rule #029 - TRIGGER_SOAR for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-030',
        'policy_name': 'Contextual Rule #030 - READ_SECRET for Admin',
        'subject_role': 'Admin',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-031',
        'policy_name': 'Contextual Rule #031 - ROTATE_KEY for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-032',
        'policy_name': 'Contextual Rule #032 - BLOCK_IP for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-033',
        'policy_name': 'Contextual Rule #033 - APPROVE_ELEVATION for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-034',
        'policy_name': 'Contextual Rule #034 - EXPORT_AUDIT_LOGS for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-035',
        'policy_name': 'Contextual Rule #035 - TRIGGER_SOAR for Admin',
        'subject_role': 'Admin',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-036',
        'policy_name': 'Contextual Rule #036 - READ_SECRET for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-037',
        'policy_name': 'Contextual Rule #037 - ROTATE_KEY for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-038',
        'policy_name': 'Contextual Rule #038 - BLOCK_IP for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-039',
        'policy_name': 'Contextual Rule #039 - APPROVE_ELEVATION for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-040',
        'policy_name': 'Contextual Rule #040 - EXPORT_AUDIT_LOGS for Admin',
        'subject_role': 'Admin',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-041',
        'policy_name': 'Contextual Rule #041 - TRIGGER_SOAR for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-042',
        'policy_name': 'Contextual Rule #042 - READ_SECRET for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-043',
        'policy_name': 'Contextual Rule #043 - ROTATE_KEY for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-044',
        'policy_name': 'Contextual Rule #044 - BLOCK_IP for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-045',
        'policy_name': 'Contextual Rule #045 - APPROVE_ELEVATION for Admin',
        'subject_role': 'Admin',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-046',
        'policy_name': 'Contextual Rule #046 - EXPORT_AUDIT_LOGS for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-047',
        'policy_name': 'Contextual Rule #047 - TRIGGER_SOAR for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-048',
        'policy_name': 'Contextual Rule #048 - READ_SECRET for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-049',
        'policy_name': 'Contextual Rule #049 - ROTATE_KEY for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-050',
        'policy_name': 'Contextual Rule #050 - BLOCK_IP for Admin',
        'subject_role': 'Admin',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-051',
        'policy_name': 'Contextual Rule #051 - APPROVE_ELEVATION for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-052',
        'policy_name': 'Contextual Rule #052 - EXPORT_AUDIT_LOGS for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-053',
        'policy_name': 'Contextual Rule #053 - TRIGGER_SOAR for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-054',
        'policy_name': 'Contextual Rule #054 - READ_SECRET for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-055',
        'policy_name': 'Contextual Rule #055 - ROTATE_KEY for Admin',
        'subject_role': 'Admin',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-056',
        'policy_name': 'Contextual Rule #056 - BLOCK_IP for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-057',
        'policy_name': 'Contextual Rule #057 - APPROVE_ELEVATION for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-058',
        'policy_name': 'Contextual Rule #058 - EXPORT_AUDIT_LOGS for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-059',
        'policy_name': 'Contextual Rule #059 - TRIGGER_SOAR for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-060',
        'policy_name': 'Contextual Rule #060 - READ_SECRET for Admin',
        'subject_role': 'Admin',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-061',
        'policy_name': 'Contextual Rule #061 - ROTATE_KEY for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-062',
        'policy_name': 'Contextual Rule #062 - BLOCK_IP for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-063',
        'policy_name': 'Contextual Rule #063 - APPROVE_ELEVATION for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-064',
        'policy_name': 'Contextual Rule #064 - EXPORT_AUDIT_LOGS for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-065',
        'policy_name': 'Contextual Rule #065 - TRIGGER_SOAR for Admin',
        'subject_role': 'Admin',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-066',
        'policy_name': 'Contextual Rule #066 - READ_SECRET for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-067',
        'policy_name': 'Contextual Rule #067 - ROTATE_KEY for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-068',
        'policy_name': 'Contextual Rule #068 - BLOCK_IP for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-069',
        'policy_name': 'Contextual Rule #069 - APPROVE_ELEVATION for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-070',
        'policy_name': 'Contextual Rule #070 - EXPORT_AUDIT_LOGS for Admin',
        'subject_role': 'Admin',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-071',
        'policy_name': 'Contextual Rule #071 - TRIGGER_SOAR for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-072',
        'policy_name': 'Contextual Rule #072 - READ_SECRET for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-073',
        'policy_name': 'Contextual Rule #073 - ROTATE_KEY for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-074',
        'policy_name': 'Contextual Rule #074 - BLOCK_IP for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-075',
        'policy_name': 'Contextual Rule #075 - APPROVE_ELEVATION for Admin',
        'subject_role': 'Admin',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-076',
        'policy_name': 'Contextual Rule #076 - EXPORT_AUDIT_LOGS for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-077',
        'policy_name': 'Contextual Rule #077 - TRIGGER_SOAR for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-078',
        'policy_name': 'Contextual Rule #078 - READ_SECRET for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-079',
        'policy_name': 'Contextual Rule #079 - ROTATE_KEY for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-080',
        'policy_name': 'Contextual Rule #080 - BLOCK_IP for Admin',
        'subject_role': 'Admin',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-081',
        'policy_name': 'Contextual Rule #081 - APPROVE_ELEVATION for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-082',
        'policy_name': 'Contextual Rule #082 - EXPORT_AUDIT_LOGS for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-083',
        'policy_name': 'Contextual Rule #083 - TRIGGER_SOAR for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-084',
        'policy_name': 'Contextual Rule #084 - READ_SECRET for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-085',
        'policy_name': 'Contextual Rule #085 - ROTATE_KEY for Admin',
        'subject_role': 'Admin',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-086',
        'policy_name': 'Contextual Rule #086 - BLOCK_IP for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-087',
        'policy_name': 'Contextual Rule #087 - APPROVE_ELEVATION for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-088',
        'policy_name': 'Contextual Rule #088 - EXPORT_AUDIT_LOGS for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-089',
        'policy_name': 'Contextual Rule #089 - TRIGGER_SOAR for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-090',
        'policy_name': 'Contextual Rule #090 - READ_SECRET for Admin',
        'subject_role': 'Admin',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-091',
        'policy_name': 'Contextual Rule #091 - ROTATE_KEY for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-092',
        'policy_name': 'Contextual Rule #092 - BLOCK_IP for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-093',
        'policy_name': 'Contextual Rule #093 - APPROVE_ELEVATION for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-094',
        'policy_name': 'Contextual Rule #094 - EXPORT_AUDIT_LOGS for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-095',
        'policy_name': 'Contextual Rule #095 - TRIGGER_SOAR for Admin',
        'subject_role': 'Admin',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-096',
        'policy_name': 'Contextual Rule #096 - READ_SECRET for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-097',
        'policy_name': 'Contextual Rule #097 - ROTATE_KEY for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-098',
        'policy_name': 'Contextual Rule #098 - BLOCK_IP for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-099',
        'policy_name': 'Contextual Rule #099 - APPROVE_ELEVATION for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-100',
        'policy_name': 'Contextual Rule #100 - EXPORT_AUDIT_LOGS for Admin',
        'subject_role': 'Admin',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-101',
        'policy_name': 'Contextual Rule #101 - TRIGGER_SOAR for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-102',
        'policy_name': 'Contextual Rule #102 - READ_SECRET for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-103',
        'policy_name': 'Contextual Rule #103 - ROTATE_KEY for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-104',
        'policy_name': 'Contextual Rule #104 - BLOCK_IP for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-105',
        'policy_name': 'Contextual Rule #105 - APPROVE_ELEVATION for Admin',
        'subject_role': 'Admin',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-106',
        'policy_name': 'Contextual Rule #106 - EXPORT_AUDIT_LOGS for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-107',
        'policy_name': 'Contextual Rule #107 - TRIGGER_SOAR for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-108',
        'policy_name': 'Contextual Rule #108 - READ_SECRET for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-109',
        'policy_name': 'Contextual Rule #109 - ROTATE_KEY for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-110',
        'policy_name': 'Contextual Rule #110 - BLOCK_IP for Admin',
        'subject_role': 'Admin',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-111',
        'policy_name': 'Contextual Rule #111 - APPROVE_ELEVATION for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-112',
        'policy_name': 'Contextual Rule #112 - EXPORT_AUDIT_LOGS for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-113',
        'policy_name': 'Contextual Rule #113 - TRIGGER_SOAR for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-114',
        'policy_name': 'Contextual Rule #114 - READ_SECRET for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-115',
        'policy_name': 'Contextual Rule #115 - ROTATE_KEY for Admin',
        'subject_role': 'Admin',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-116',
        'policy_name': 'Contextual Rule #116 - BLOCK_IP for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-117',
        'policy_name': 'Contextual Rule #117 - APPROVE_ELEVATION for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-118',
        'policy_name': 'Contextual Rule #118 - EXPORT_AUDIT_LOGS for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-119',
        'policy_name': 'Contextual Rule #119 - TRIGGER_SOAR for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-120',
        'policy_name': 'Contextual Rule #120 - READ_SECRET for Admin',
        'subject_role': 'Admin',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-121',
        'policy_name': 'Contextual Rule #121 - ROTATE_KEY for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-122',
        'policy_name': 'Contextual Rule #122 - BLOCK_IP for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-123',
        'policy_name': 'Contextual Rule #123 - APPROVE_ELEVATION for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-124',
        'policy_name': 'Contextual Rule #124 - EXPORT_AUDIT_LOGS for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-125',
        'policy_name': 'Contextual Rule #125 - TRIGGER_SOAR for Admin',
        'subject_role': 'Admin',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-126',
        'policy_name': 'Contextual Rule #126 - READ_SECRET for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-127',
        'policy_name': 'Contextual Rule #127 - ROTATE_KEY for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-128',
        'policy_name': 'Contextual Rule #128 - BLOCK_IP for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-129',
        'policy_name': 'Contextual Rule #129 - APPROVE_ELEVATION for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-130',
        'policy_name': 'Contextual Rule #130 - EXPORT_AUDIT_LOGS for Admin',
        'subject_role': 'Admin',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-131',
        'policy_name': 'Contextual Rule #131 - TRIGGER_SOAR for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-132',
        'policy_name': 'Contextual Rule #132 - READ_SECRET for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-133',
        'policy_name': 'Contextual Rule #133 - ROTATE_KEY for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-134',
        'policy_name': 'Contextual Rule #134 - BLOCK_IP for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-135',
        'policy_name': 'Contextual Rule #135 - APPROVE_ELEVATION for Admin',
        'subject_role': 'Admin',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-136',
        'policy_name': 'Contextual Rule #136 - EXPORT_AUDIT_LOGS for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-137',
        'policy_name': 'Contextual Rule #137 - TRIGGER_SOAR for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-138',
        'policy_name': 'Contextual Rule #138 - READ_SECRET for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-139',
        'policy_name': 'Contextual Rule #139 - ROTATE_KEY for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-140',
        'policy_name': 'Contextual Rule #140 - BLOCK_IP for Admin',
        'subject_role': 'Admin',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-141',
        'policy_name': 'Contextual Rule #141 - APPROVE_ELEVATION for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-142',
        'policy_name': 'Contextual Rule #142 - EXPORT_AUDIT_LOGS for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-143',
        'policy_name': 'Contextual Rule #143 - TRIGGER_SOAR for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-144',
        'policy_name': 'Contextual Rule #144 - READ_SECRET for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-145',
        'policy_name': 'Contextual Rule #145 - ROTATE_KEY for Admin',
        'subject_role': 'Admin',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-146',
        'policy_name': 'Contextual Rule #146 - BLOCK_IP for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-147',
        'policy_name': 'Contextual Rule #147 - APPROVE_ELEVATION for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-148',
        'policy_name': 'Contextual Rule #148 - EXPORT_AUDIT_LOGS for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-149',
        'policy_name': 'Contextual Rule #149 - TRIGGER_SOAR for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-150',
        'policy_name': 'Contextual Rule #150 - READ_SECRET for Admin',
        'subject_role': 'Admin',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-151',
        'policy_name': 'Contextual Rule #151 - ROTATE_KEY for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-152',
        'policy_name': 'Contextual Rule #152 - BLOCK_IP for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-153',
        'policy_name': 'Contextual Rule #153 - APPROVE_ELEVATION for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-154',
        'policy_name': 'Contextual Rule #154 - EXPORT_AUDIT_LOGS for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-155',
        'policy_name': 'Contextual Rule #155 - TRIGGER_SOAR for Admin',
        'subject_role': 'Admin',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-156',
        'policy_name': 'Contextual Rule #156 - READ_SECRET for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-157',
        'policy_name': 'Contextual Rule #157 - ROTATE_KEY for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-158',
        'policy_name': 'Contextual Rule #158 - BLOCK_IP for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-159',
        'policy_name': 'Contextual Rule #159 - APPROVE_ELEVATION for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-160',
        'policy_name': 'Contextual Rule #160 - EXPORT_AUDIT_LOGS for Admin',
        'subject_role': 'Admin',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-161',
        'policy_name': 'Contextual Rule #161 - TRIGGER_SOAR for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-162',
        'policy_name': 'Contextual Rule #162 - READ_SECRET for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-163',
        'policy_name': 'Contextual Rule #163 - ROTATE_KEY for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-164',
        'policy_name': 'Contextual Rule #164 - BLOCK_IP for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-165',
        'policy_name': 'Contextual Rule #165 - APPROVE_ELEVATION for Admin',
        'subject_role': 'Admin',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-166',
        'policy_name': 'Contextual Rule #166 - EXPORT_AUDIT_LOGS for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-167',
        'policy_name': 'Contextual Rule #167 - TRIGGER_SOAR for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-168',
        'policy_name': 'Contextual Rule #168 - READ_SECRET for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-169',
        'policy_name': 'Contextual Rule #169 - ROTATE_KEY for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-170',
        'policy_name': 'Contextual Rule #170 - BLOCK_IP for Admin',
        'subject_role': 'Admin',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-171',
        'policy_name': 'Contextual Rule #171 - APPROVE_ELEVATION for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-172',
        'policy_name': 'Contextual Rule #172 - EXPORT_AUDIT_LOGS for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-173',
        'policy_name': 'Contextual Rule #173 - TRIGGER_SOAR for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-174',
        'policy_name': 'Contextual Rule #174 - READ_SECRET for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'READ_SECRET',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-175',
        'policy_name': 'Contextual Rule #175 - ROTATE_KEY for Admin',
        'subject_role': 'Admin',
        'target_action': 'ROTATE_KEY',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-176',
        'policy_name': 'Contextual Rule #176 - BLOCK_IP for Analyst',
        'subject_role': 'Analyst',
        'target_action': 'BLOCK_IP',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-177',
        'policy_name': 'Contextual Rule #177 - APPROVE_ELEVATION for DevOps',
        'subject_role': 'DevOps',
        'target_action': 'APPROVE_ELEVATION',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-178',
        'policy_name': 'Contextual Rule #178 - EXPORT_AUDIT_LOGS for Auditor',
        'subject_role': 'Auditor',
        'target_action': 'EXPORT_AUDIT_LOGS',
        'required_mfa': True,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
    {
        'policy_id': 'ABAC-POL-179',
        'policy_name': 'Contextual Rule #179 - TRIGGER_SOAR for SecurityEngineer',
        'subject_role': 'SecurityEngineer',
        'target_action': 'TRIGGER_SOAR',
        'required_mfa': False,
        'allowed_subnets': ['10.0.0.0/8', '192.168.1.0/24', '172.16.0.0/12'],
        'time_window_start': '08:00',
        'time_window_end': '20:00',
        'max_risk_score': 85,
        'effect': 'PERMIT',
        'is_active': True
    },
]

def evaluate_enterprise_abac_rule(subject: Dict[str, Any], action: str, context: Dict[str, Any]) -> bool:
    """Evaluate contextual subject and environment attributes against the ABAC matrix."""
    user_role = subject.get('role', 'Viewer')
    mfa_active = subject.get('mfa_enabled', False)
    client_ip = context.get('ip_address', '127.0.0.1')
    
    for pol in ENTERPRISE_ABAC_POLICIES:
        if pol['subject_role'] == user_role and pol['target_action'] == action:
            if pol['required_mfa'] and not mfa_active:
                return False
            return True
    return False
